//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSIT143_2_Team2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MingSuEntities1 : DbContext
    {
        public MingSuEntities1()
            : base("name=MingSuEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<ActivityReference> ActivityReferences { get; set; }
        public virtual DbSet<Add> Adds { get; set; }
        public virtual DbSet<AddCatergory> AddCatergories { get; set; }
        public virtual DbSet<AddReference> AddReferences { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<AdminReference> AdminReferences { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<EquipmentCatergory> EquipmentCatergories { get; set; }
        public virtual DbSet<EquipmentReference> EquipmentReferences { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<ImageReference> ImageReferences { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<OrderStatu> OrderStatus { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<RoomStatu> RoomStatus { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
